name: Go

on:
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
      - release-*
      - backplane-*

env:
  # Common versions
  GO_VERSION: '1.19'
  GO_REQUIRED_MIN_VERSION: ''
  IMAGEBUILDER_VERSION: '1.2.3'
defaults:
  run:
    working-directory: go/src/open-cluster-management.io/work

jobs:
  verify:
    name: verify
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: go/src/open-cluster-management.io/work
      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: verify
        run: make verify
  
  verify-deps:
    name: verify-deps
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: go/src/open-cluster-management.io/work
      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: verify-deps
        run: make verify-deps

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: go/src/open-cluster-management.io/work
      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: build
        run: make build
  
  unit:
    name: unit
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: go/src/open-cluster-management.io/work
      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: unit
        run: make test

  integration:
    name: integration
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: go/src/open-cluster-management.io/work
      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: integration
        run: make test-integration
  
  e2e:
    name: e2e
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: go/src/open-cluster-management.io/work
      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: install imagebuilder
        run: go install github.com/openshift/imagebuilder/cmd/imagebuilder@v${{ env.IMAGEBUILDER_VERSION }}
      - name: images
        run: make images
        env:
          IMAGE_REGISTRY: quay.io/stolostron
          IMAGE_TAG: e2e
      - name: setup kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: v0.17.0
      - name: Load image on the nodes of the cluster
        run: kind load docker-image --name=kind ${IMAGE_REGISTRY}/work:${IMAGE_TAG}
        env:
          IMAGE_REGISTRY: quay.io/stolostron
          IMAGE_TAG: e2e
      - name: Run e2e test
        run: make test-e2e
        env:
          KUBECONFIG: /home/runner/.kube/config
          IMAGE_REGISTRY: quay.io/stolostron
          IMAGE_TAG: e2e
          IMAGE_NAME: quay.io/stolostron/work:e2e
